"use client"

import { useState, useMemo } from "react"
import type {
  Payment,
  PaymentCreatePayload,
  PaymentUpdatePayload,
  PaymentStatus,
  PaymentMethod,
} from "@/types/payment"
import type { Contract } from "@/types/contract"
import type { Property } from "@/types/property"
import type { Tenant } from "@/types/tenant"
import type { Lease } from "@/types/lease"
import type { BillingRecord } from "@/types/billing"
import { ApiError } from "@/types"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import {
  Combobox,
  ComboboxInputGroup,
  ComboboxInput,
  ComboboxClear,
  ComboboxContent,
  ComboboxEmpty,
  ComboboxList,
  ComboboxItem,
} from "@/components/ui/combobox"
import { Button } from "@/components/ui/button"
import { billingRecordLabel, contractLabel } from "@/lib/utils"

// ─── Payment Form ───────────────────────────────────────────────────────────

// Single source of truth for enum → label — used for both the select trigger's
// display value and its dropdown options, so they can't drift out of sync.
const PAYMENT_STATUS_LABELS: Record<PaymentStatus, string> = {
  PAID: "Paid",
  PENDING: "Pending",
  VOIDED: "Voided",
  REFUNDED: "Refunded",
}

// Values must stay lowercase, matching PAYMENT_METHODS in the backend's
// app/models/payment.py exactly — the DB's ck_payment_method CHECK
// constraint is case-sensitive.
const PAYMENT_METHOD_LABELS: Record<PaymentMethod, string> = {
  cash: "Cash",
  "bank transfer": "Bank transfer",
  gcash: "GCash",
  maya: "Maya",
  check: "Check",
}

interface ReferenceNumberFormat {
  required: boolean
  pattern?: RegExp
  hint: string
  disabled?: boolean
}

// Mirrors the backend's per-payment-method reference_number rules (issue #18).
// Keys must stay in lockstep with PAYMENT_METHOD_LABELS above — both are keyed
// by PaymentMethod, so the compiler enforces they can't silently diverge.
const REFERENCE_NUMBER_FORMATS: Record<PaymentMethod, ReferenceNumberFormat> = {
  cash: {
    required: false,
    disabled: true,
    hint: "Auto-generated by the system after saving.",
  },
  check: {
    required: true,
    pattern: /^\d{4,10}$/,
    hint: "4–10 digits.",
  },
  gcash: {
    required: true,
    pattern: /^\d{13}$/,
    hint: "Exactly 13 digits.",
  },
  "bank transfer": {
    required: true,
    pattern: /^[A-Za-z0-9-]{6,34}$/,
    hint: "6–34 letters, numbers, or dashes.",
  },
  maya: {
    required: true,
    pattern: /^[A-Za-z0-9-]{6,34}$/,
    hint: "6–34 letters, numbers, or dashes.",
  },
}

function isReferenceNumberValid(format: ReferenceNumberFormat | undefined, value: string): boolean {
  if (!format || format.disabled) return true
  const trimmed = value.trim()
  if (format.required && !trimmed) return false
  if (trimmed && format.pattern && !format.pattern.test(trimmed)) return false
  return true
}

function referenceNumberErrorMessage(
  format: ReferenceNumberFormat | undefined,
  value: string
): string | null {
  if (!format || format.disabled) return null
  const trimmed = value.trim()
  if (format.required && !trimmed) return "Required for this payment method."
  if (trimmed && format.pattern && !format.pattern.test(trimmed)) return `Must be ${format.hint}`
  return null
}

interface PaymentFormProps {
  payment?: Payment
  contracts: Contract[]
  properties: Property[]
  tenants: Tenant[]
  leases: Lease[]
  billingRecords: BillingRecord[]
  onSubmit: (payload: PaymentCreatePayload | PaymentUpdatePayload) => Promise<void>
  onCancel: () => void
  onError?: (message: string) => void
  onContractChange?: (contractId: string) => void
}

export function PaymentForm({
  payment,
  contracts,
  properties,
  tenants,
  leases,
  billingRecords,
  onSubmit,
  onCancel,
  onError,
  onContractChange,
}: PaymentFormProps) {
  const isEdit = !!payment

  const [contractId, setContractId] = useState(payment?.contract_id ?? "")
  const [billingRecordId, setBillingRecordId] = useState(payment?.billing_record_id ?? "")
  const [amount, setAmount] = useState(payment?.amount ?? "")
  const [paidAt, setPaidAt] = useState(payment ? payment.paid_at.slice(0, 10) : "")
  const [paymentMethod, setPaymentMethod] = useState(payment?.payment_method ?? "")
  const [status, setStatus] = useState<PaymentStatus>(payment?.status ?? "PAID")
  const [referenceNumber, setReferenceNumber] = useState(payment?.reference_number ?? "")
  const [referenceNumberTouched, setReferenceNumberTouched] = useState(false)
  const [referenceNumberServerError, setReferenceNumberServerError] = useState<string | null>(null)

  const [loading, setLoading] = useState(false)

  const referenceNumberFormat = REFERENCE_NUMBER_FORMATS[paymentMethod as PaymentMethod]

  // The backend only re-validates reference_number when it's actually part of
  // the PATCH payload (see handleSubmit's diffing below) — so an existing,
  // unchanged reference number that predates today's format rules must not
  // block saving unrelated edits in edit mode.
  const referenceNumberWillBeSubmitted =
    !isEdit ||
    paymentMethod !== (payment?.payment_method ?? "") ||
    referenceNumber !== (payment?.reference_number ?? "")

  const requiredFilled =
    (isEdit || (contractId.trim() && amount.trim())) &&
    (!referenceNumberWillBeSubmitted ||
      isReferenceNumberValid(referenceNumberFormat, referenceNumber))

  const selectedContract = contracts.find((c) => c.id === contractId) ?? null

  // A billing record only belongs to the selected contract if its lease does —
  // BillingRecord has no contract_id of its own, so this has to join through
  // Lease.contract_id (see leaseLabel/billingRecordLabel in @/lib/utils).
  const contractLeaseIds = useMemo(
    () => new Set(leases.filter((l) => l.contract_id === contractId).map((l) => l.id)),
    [leases, contractId]
  )
  const scopedBillingRecords = useMemo(
    () => billingRecords.filter((r) => contractLeaseIds.has(r.lease_id)),
    [billingRecords, contractLeaseIds]
  )

  const selectedBillingRecord = scopedBillingRecords.find((r) => r.id === billingRecordId) ?? null

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setLoading(true)
    try {
      if (isEdit) {
        const payload: PaymentUpdatePayload = {}
        if (amount !== payment.amount) payload.amount = amount
        // paid_at requires a full ISO date-time; the native date input only ever
        // gives us a date, so anchor it to an explicit, arbitrary midnight UTC
        // rather than fabricating a real time of day the user never specified.
        if (paidAt !== payment.paid_at.slice(0, 10)) payload.paid_at = `${paidAt}T00:00:00.000Z`
        if (paymentMethod !== (payment.payment_method ?? ""))
          payload.payment_method = (paymentMethod as PaymentMethod) || null
        if (status !== payment.status) payload.status = status
        const effectiveReferenceNumber = referenceNumberFormat?.disabled
          ? null
          : referenceNumber || null
        if (effectiveReferenceNumber !== (payment.reference_number ?? null))
          payload.reference_number = effectiveReferenceNumber
        await onSubmit(payload)
      } else {
        const payload: PaymentCreatePayload = {
          contract_id: contractId,
          billing_record_id: billingRecordId || null,
          amount,
          paid_at: paidAt ? `${paidAt}T00:00:00.000Z` : undefined,
          payment_method: (paymentMethod as PaymentMethod) || null,
          reference_number: referenceNumberFormat?.disabled ? null : referenceNumber || null,
        }
        await onSubmit(payload)
      }
    } catch (err: unknown) {
      if (err instanceof ApiError && err.fieldErrors?.reference_number) {
        setReferenceNumberServerError(err.fieldErrors.reference_number)
      } else {
        onError?.(err instanceof Error ? err.message : "Something went wrong")
      }
    } finally {
      setLoading(false)
    }
  }

  return (
    <form onSubmit={handleSubmit} noValidate className="space-y-4">
      {!isEdit && (
        <div className="space-y-1.5">
          <Label htmlFor="payment_contract_id">Contract</Label>
          <Combobox
            items={contracts}
            value={selectedContract}
            onValueChange={(contract: Contract | null) => {
              const newContractId = contract?.id ?? ""
              setContractId(newContractId)
              onContractChange?.(newContractId)
              if (billingRecordId) {
                const currentRecord = billingRecords.find((r) => r.id === billingRecordId)
                const stillValid =
                  !!currentRecord &&
                  leases.some(
                    (l) => l.id === currentRecord.lease_id && l.contract_id === newContractId
                  )
                if (!stillValid) setBillingRecordId("")
              }
            }}
            itemToStringLabel={(contract: Contract) => contractLabel(contract, properties, tenants)}
            disabled={loading}
          >
            <ComboboxInputGroup>
              <ComboboxInput
                id="payment_contract_id"
                placeholder="Search contracts by property or tenant…"
                required
              />
              <ComboboxClear />
            </ComboboxInputGroup>
            <ComboboxContent>
              <ComboboxEmpty>No contracts found.</ComboboxEmpty>
              <ComboboxList>
                {(contract: Contract) => (
                  <ComboboxItem key={contract.id} value={contract}>
                    {contractLabel(contract, properties, tenants)}
                  </ComboboxItem>
                )}
              </ComboboxList>
            </ComboboxContent>
          </Combobox>
        </div>
      )}

      <div className="grid grid-cols-2 gap-3">
        <div className="space-y-1.5">
          <Label htmlFor="payment_amount">Amount</Label>
          <Input
            id="payment_amount"
            type="number"
            step="0.01"
            value={amount}
            onChange={(e) => setAmount(e.target.value)}
            placeholder="15000.00"
            disabled={loading}
            required
          />
        </div>
        <div className="space-y-1.5">
          <Label htmlFor="payment_paid_at">Paid on</Label>
          <Input
            id="payment_paid_at"
            type="date"
            value={paidAt}
            onChange={(e) => setPaidAt(e.target.value)}
            disabled={loading}
          />
        </div>
      </div>

      {!isEdit && (
        <div className="space-y-1.5">
          <Label htmlFor="payment_billing_record_id">Billing record</Label>
          <Combobox
            items={scopedBillingRecords}
            value={selectedBillingRecord}
            onValueChange={(record: BillingRecord | null) => setBillingRecordId(record?.id ?? "")}
            itemToStringLabel={(record: BillingRecord) =>
              billingRecordLabel(record, leases, contracts, properties, tenants)
            }
            disabled={loading}
          >
            <ComboboxInputGroup>
              <ComboboxInput
                id="payment_billing_record_id"
                placeholder="Search by lease, period, or status…"
              />
              <ComboboxClear />
            </ComboboxInputGroup>
            <ComboboxContent>
              <ComboboxEmpty>
                No billing records checked yet — generate or refresh one above first.
              </ComboboxEmpty>
              <ComboboxList>
                {(record: BillingRecord) => (
                  <ComboboxItem key={record.id} value={record}>
                    {billingRecordLabel(record, leases, contracts, properties, tenants)}
                  </ComboboxItem>
                )}
              </ComboboxList>
            </ComboboxContent>
          </Combobox>
        </div>
      )}

      <div className="grid grid-cols-2 gap-3">
        <div className="space-y-1.5">
          <Label htmlFor="payment_method">Method</Label>
          <Select
            value={paymentMethod || "__unspecified__"}
            onValueChange={(v: string | null) => {
              setPaymentMethod(!v || v === "__unspecified__" ? "" : v)
              setReferenceNumberServerError(null)
            }}
            disabled={loading}
          >
            <SelectTrigger id="payment_method">
              <SelectValue>
                {(value: string) =>
                  value === "__unspecified__"
                    ? "Not specified"
                    : PAYMENT_METHOD_LABELS[value as PaymentMethod]
                }
              </SelectValue>
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="__unspecified__">Not specified</SelectItem>
              {(Object.keys(PAYMENT_METHOD_LABELS) as PaymentMethod[]).map((value) => (
                <SelectItem key={value} value={value}>
                  {PAYMENT_METHOD_LABELS[value]}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-1.5">
          <Label htmlFor="payment_reference_number">Reference number</Label>
          <Input
            id="payment_reference_number"
            value={referenceNumber ?? ""}
            onChange={(e) => {
              setReferenceNumber(e.target.value)
              setReferenceNumberServerError(null)
            }}
            onBlur={() => setReferenceNumberTouched(true)}
            disabled={loading || !!referenceNumberFormat?.disabled}
          />
          {(() => {
            const error =
              referenceNumberServerError ??
              (referenceNumberTouched
                ? referenceNumberErrorMessage(referenceNumberFormat, referenceNumber)
                : null)
            if (error) return <p className="text-destructive text-xs">{error}</p>
            if (referenceNumberFormat)
              return <p className="text-muted-foreground text-xs">{referenceNumberFormat.hint}</p>
            return null
          })()}
        </div>
      </div>

      {isEdit && (
        <div className="space-y-1.5">
          <Label>Status</Label>
          <Select
            value={status}
            onValueChange={(v) => setStatus(v as PaymentStatus)}
            disabled={loading}
          >
            <SelectTrigger>
              <SelectValue>{(value: PaymentStatus) => PAYMENT_STATUS_LABELS[value]}</SelectValue>
            </SelectTrigger>
            <SelectContent>
              {(Object.keys(PAYMENT_STATUS_LABELS) as PaymentStatus[]).map((value) => (
                <SelectItem key={value} value={value}>
                  {PAYMENT_STATUS_LABELS[value]}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      )}

      <div className="flex justify-end gap-2 pt-2">
        <Button type="button" variant="outline" onClick={onCancel} disabled={loading}>
          Cancel
        </Button>
        <Button
          type="submit"
          disabled={loading || !requiredFilled}
          className="bg-gradient-to-r from-[#E61E4D] via-[#E31C5F] to-[#D70466] text-white hover:opacity-95"
        >
          {loading
            ? isEdit
              ? "Saving…"
              : "Recording…"
            : isEdit
              ? "Save changes"
              : "Record payment"}
        </Button>
      </div>
    </form>
  )
}
